export const dummy = {
  dates: {
    maximum: "2023-08-12",
    minimum: "2023-06-25",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/tTfnd2VrlaZJSBD9HUbtSF3CqPJ.jpg",
      genre_ids: [35, 12, 14],
      id: 346698,
      original_language: "en",
      original_title: "Barbie",
      overview:
        "원하는 무엇이든 될 수 있는 바비랜드에서 살아가던 바비가 현실 세계와 이어진 포털의 균열을 발견하게 되고, 이를 해결하기 위해 켄과 예기치 못한 여정을 떠나면서 펼쳐지는 이야기",
      popularity: 2588.653,
      poster_path: "/rt8sHzR0XUyKHxU75ZIWs7MsNEN.jpg",
      release_date: "2023-07-19",
      title: "바비",
      video: false,
      vote_average: 7.5,
      vote_count: 2931,
    },
    {
      adult: false,
      backdrop_path: "/hPcP1kv6vrkRmQO3YgV1H97FE5Q.jpg",
      genre_ids: [27, 9648, 53],
      id: 614479,
      original_language: "en",
      original_title: "Insidious: The Red Door",
      overview:
        "10년 전, 유체이탈을 통해 기이한 사건을 겪은 '조쉬'와 '달튼' 부자는 그날의 기억을 모두 지운다. 10년 후,'조쉬'는 수상한 존재가 주변을 맴돌고 있음을 느끼고, 집을 떠나 대학에 입학한 ‘달튼'은 봉인된 기억 속 빨간 문에 대한 의문을 품게 된다. 램버트 가족에게 연달아 기괴한 사건들이 일어나고 과거의 비밀이 끔찍한 악몽으로 되살아나는데…",
      popularity: 2559.79,
      poster_path: "/4UCQWDmMsOxqgtdTbkihSXbexbf.jpg",
      release_date: "2023-07-19",
      title: "인시디어스: 빨간 문",
      video: false,
      vote_average: 6.9,
      vote_count: 790,
    },
    {
      adult: false,
      backdrop_path: "/f7UI3dYpr7ZUHGo0iIr1Qvy1VPe.jpg",
      genre_ids: [16, 10751, 14, 35],
      id: 1040148,
      original_language: "en",
      original_title: "Ruby Gillman, Teenage Kraken",
      overview:
        "평범함 뒤에 숨겨진 능력을 가진 반전캐 크라켄 ‘루비’와  검은 속마음을 숨긴 사기캐 빌런 인어 ‘첼시’의 대결을 그린 드림웍스 제작진의 썸머 오션 어드벤처!",
      popularity: 1118.854,
      poster_path: "/pUv9neufsz8hsXoIN5KkAeNZLgl.jpg",
      release_date: "2023-07-25",
      title: "틴에이지 크라켄 루비",
      video: false,
      vote_average: 7.6,
      vote_count: 510,
    },
    {
      adult: false,
      backdrop_path: "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
      genre_ids: [28, 12, 53],
      id: 575264,
      original_language: "en",
      original_title: "Mission: Impossible - Dead Reckoning Part One",
      overview:
        "모든 인류를 위협할 새로운 무기를 추적하게 된 에단 헌트와 IMF팀은 이 무기가 인류의 미래를 통제할 수 있다는 사실을 알게 된다. 전 세계가 위태로운 상황에 처한 가운데, 이를 추적하던 에단 헌트에게 어둠의 세력까지 접근하고 마침내 미스터리하고 강력한 빌런과 마주하게 된 그는 가장 위험한 작전을 앞두고 자신이 아끼는 사람들의 생명과 중요한 임무 사이에서 선택을 해야 하는 상황에 놓이게 되는데…",
      popularity: 619.506,
      poster_path: "/nQsWPG020kSWdOl3EhFXRNE2s0n.jpg",
      release_date: "2023-07-12",
      title: "미션 임파서블: 데드 레코닝 PART ONE",
      video: false,
      vote_average: 7.7,
      vote_count: 976,
    },
    {
      adult: false,
      backdrop_path: "/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg",
      genre_ids: [12, 28, 14],
      id: 335977,
      original_language: "en",
      original_title: "Indiana Jones and the Dial of Destiny",
      overview:
        "1969년 뉴욕, 전설적인 모험가이자 고고학자 인디아나 존스 앞에 대녀 헬레나와 오랜 숙적 위르겐 폴러의 세력이 등장한다. 그들의 목표는 단 하나, 운명의 다이얼. 역사의 흐름을 바꿀 수 있는 다이얼을 차지하려는 쫓고 쫓기는 위협 속에 인디아나 존스는 전 세계를 무대로 하는 새로운 모험에 뛰어드는데…",
      popularity: 289.992,
      poster_path: "/8ifAx8GS5AHL7xOTMJDMaza84RQ.jpg",
      release_date: "2023-06-28",
      title: "인디아나 존스: 운명의 다이얼",
      video: false,
      vote_average: 6.6,
      vote_count: 935,
    },
    {
      adult: false,
      backdrop_path: "/qwp5hqxrOHfCyBP8vLG8vxXvxho.jpg",
      genre_ids: [16, 28, 80, 9648],
      id: 1047041,
      original_language: "ja",
      original_title: "名探偵コナン 黒鉄の魚影（サブマリン）",
      overview:
        "인터폴의 최첨단 정보 해양 시설인 퍼시픽 부이. 일본과 유럽의 CCTV 정보를 확인할 수 있을 뿐 아니라, 장기 수배범이나 유괴당한 피해자를 전 세계에서 찾아낼 수 있는 전연령 인식이라는 획기적인 AI 기술을 개발 중이다. 그러던 중 독일에서 검은 조직에 의해 유로폴 직원이 살해되는 사건이 발생하고 뒤를 이어 전연령 인식의 핵심 기술자가 납치된다. 나이와 상관없이 안면 인식이 가능한 기술이 검은 조직의 손에 들어가면 독약 APTX4869 개발 후 사망한 것으로 알려진 코드명 셰리이자 하이바라 아이도 위험하게 되는데...",
      popularity: 233.161,
      poster_path: "/wBdLreR2YI2ZAYGk7c4Zy2qJU2d.jpg",
      release_date: "2023-07-20",
      title: "명탐정코난: 흑철의 어영",
      video: false,
      vote_average: 6.5,
      vote_count: 25,
    },
    {
      adult: false,
      backdrop_path: "/8FJcYW6YuUQ7x4eEqPlVi10ELYM.jpg",
      genre_ids: [18, 10749],
      id: 1064662,
      original_language: "ja",
      original_title: "美しい彼～eternal～",
      overview:
        "말더듬증으로 언제나 학급에서 외톨이였던 ‘히라’가 첫눈에 사랑에 빠진 것은 학교 최고의 인기인으로 군림하는, 아름다운 킹 ‘키요이’였다.  고등학교를 졸업하고 연인 사이가 된 ‘히라’와 ‘키요이’. 두 사람은 ‘히라’의 집에서 행복한 동거생활을 시작하지만, 사진작가 어시스던트로 일하는 '히라'와 배우의 길을 걷는 '키요이' 사이에 조금씩 균열이 생기기 시작하는데...  ‘키요이’는 킹이자 유일한 아름다움이라고 생각하는 ‘히라’와 그런 ‘히라’와 대등한 보통의 연인이 되고 싶은 ‘키요이’.  ‘구원’에서 ‘영원’이 될 두 사람의 새로운 이야기가 시작된다!",
      popularity: 198.782,
      poster_path: "/1ifuQcCLTefzwtAKJEXxqHNqDMF.jpg",
      release_date: "2023-07-12",
      title: "극장판 아름다운 그: 이터널",
      video: false,
      vote_average: 8.8,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/Als2QyqbLgT5G3rwTGJta8QQfqP.jpg",
      genre_ids: [35, 14],
      id: 616747,
      original_language: "en",
      original_title: "Haunted Mansion",
      overview:
        "뉴올리언스의 대저택으로 이사 온 개비와 아들 트래비스. 겉모습부터 심상치 않은 이곳엔 알고 보니 999명의 유령이 살고 있다. 유령들을 내쫓아 달라는 개비의 요청에 저택으로 모여든 겁 없는 유령 전문가들. 하지만 호기로움도 잠시, 곳곳에서 벌어지는 기상천외한 일들에 사투를 펼치게 되는데… 과연, 이들은 유령들을 쫓고 집을 되찾을 수 있을까?",
      popularity: 178.606,
      poster_path: "/oYfssARSMGcHk6RPLwSARsTURmC.jpg",
      release_date: "2023-07-26",
      title: "헌티드 맨션",
      video: false,
      vote_average: 7,
      vote_count: 131,
    },
    {
      adult: false,
      backdrop_path: "/9lIK95xch2fGQEVnBw7BwQMjP8z.jpg",
      genre_ids: [18, 12, 878, 10751],
      id: 864101,
      original_language: "ru",
      original_title: "Мира",
      overview:
        "‘우주정거장 미르’에서는 24시간 뒤 지나갈 소행성을 추적 중 운석 충돌 가능성을 말하지만 무시되고 만다.  한편 지구에서는 이러한 영문도 모른 채  지구를 비켜갈 화려한 유성우의 우주쇼를 볼 기대에 들떠 있다.  그 시각, 소행성 뒤편 사각 지대의 운석 파편들이 핵폭탄보다 10배 강력한 파워로 우주정거장을 파괴한 후 지구를 향해 나아가고 소행성에 강타당한 지구는 모든 건물과 도로가 붕괴되며 대재앙이 펼쳐지는데...",
      popularity: 144.24,
      poster_path: "/oYy2fIQBxp1IlQ6oqE6KQoTXqD.jpg",
      release_date: "2023-07-05",
      title: "플래닛",
      video: false,
      vote_average: 6.5,
      vote_count: 18,
    },
    {
      adult: false,
      backdrop_path: "/63CDysgJZb38ZXdw2yF1UuDJgDN.jpg",
      genre_ids: [53],
      id: 979924,
      original_language: "en",
      original_title: "On the Line",
      overview:
        "심야 라디오 '온 더 라인'의 진행자 엘리스가 생방송 중 의문의 전화를 받게 되고, 쇼맨은 그의 온 가족을 죽이겠다고 협박을 한다. 모든 것이 실시간으로 진행되는 라디오에서 사랑하는 사람을 구하기 위한 엘리스의 고군분투 생존게임이 시작되는데...",
      popularity: 130.961,
      poster_path: "/o04KUuO9Zoi1L8KxH5Z4jJF7iXb.jpg",
      release_date: "2023-08-02",
      title: "온 더 라인",
      video: false,
      vote_average: 6.2,
      vote_count: 355,
    },
    {
      adult: false,
      backdrop_path: "/sbtJ1SxJ1CIvttQqhGbUZcDpSqC.jpg",
      genre_ids: [35, 18],
      id: 747188,
      original_language: "en",
      original_title: "Asteroid City",
      overview:
        "1955년 가상의 사막 도시이자 운석이 떨어진 도시 애스터로이드 시티. 매년 운석이 떨어진 것을 기념하는 소행성의 날 행사에 모인 사람들은 예상치 못한 사건으로 인해 그 곳에 옴짝달싹도 못한 채 갇히게 되고 계속해서 생각지도 못한 예측불허 상황들이 펼쳐지는데…",
      popularity: 113.344,
      poster_path: "/hmqczDa2B81Znu4QUUxCv8I6Yfd.jpg",
      release_date: "2023-06-28",
      title: "애스터로이드 시티",
      video: false,
      vote_average: 6.7,
      vote_count: 576,
    },
    {
      adult: false,
      backdrop_path: "/o3YleBe0QGNNlUqm6CnJVqGQQH4.jpg",
      genre_ids: [35, 12, 14],
      id: 798286,
      original_language: "en",
      original_title: "Beau Is Afraid",
      overview:
        "아버지가 누군지 모른 채 사랑하는 독단적인 어머니와 살며 상처받은 중년 남자 보는 매사 두렵고 불안하지만 그렇지 않은 척하기 일쑤이다. 그런 그가 어머니를 만나러 고향으로 돌아가던 길에 초현실적인 상황과 직면하게 되는데…",
      popularity: 66.658,
      poster_path: "/pU8F9qKSoiqcv1nnaYezBzp7MoZ.jpg",
      release_date: "2023-07-05",
      title: "보 이즈 어프레이드",
      video: false,
      vote_average: 6.9,
      vote_count: 456,
    },
    {
      adult: false,
      backdrop_path: "/kpzDQtFbw3dWoFxabydK9tlvWJm.jpg",
      genre_ids: [16, 10751],
      id: 778810,
      original_language: "en",
      original_title: "Fireheart",
      overview:
        "1932년 뉴욕, 브로드웨이 극장가를 노리는 연쇄 방화 사건 발생! 800명의 소방관이 실종되는 전대미문의 사건으로 혼란에 빠진 뉴욕의 ‘지미 시장’은 은퇴한 소방관 ‘숀’을 다시 불러 긴급 소방팀을 꾸린다. 어릴 때부터 아버지 ‘숀’처럼 멋진 소방관이 되고 싶은 꿈을 가진 ‘조지아’는 초보 소방관 ‘조’로 감쪽같이 변장해 긴급 소방팀에 몰래 합류하는 데 성공하는데… 방화범을 잡기 위한 소방 대작전 개시! 의욕은 충만! 실전 경험 전무! 과연 조지아와 초보 소방팀은 최악의 위기에 처한 뉴욕시를 구할 수 있을 것인가..!",
      popularity: 43.283,
      poster_path: "/1VQHNwsuLdCiXgPpWqPz0yKUyB4.jpg",
      release_date: "2023-06-28",
      title: "파이어하트",
      video: false,
      vote_average: 7.4,
      vote_count: 215,
    },
    {
      adult: false,
      backdrop_path: "/a9tg4d2qbLcbt22UqtqTvz6VQWS.jpg",
      genre_ids: [18, 36],
      id: 761851,
      original_language: "en",
      original_title: "His Only Son",
      overview:
        "어느 날 밤, 하나님이 아브라함을 찾아와 모리아 땅으로 가서 외아들 이삭을 번제로 바치라고 명령하신다. 아브라함은 다음 날 아내 사라를 뒤로 한 채 이삭과 3일간의 험난한 여정을 시작한다. “왜 하필 100살에 낳은 아들 이삭을 제물로 바치라고 하시는 걸까?” “왜 하필 3일이나 가야 하는 모리아에서 제사를 드리라고 하시는 걸까?” 탄식으로 가득한 질문은 여정 내내 계속되지만 마침내 예루살렘 모리아 산에서 그 해답을 찾게 되는데..",
      popularity: 43.133,
      poster_path: "/rMj7NoTvjX10ofo5Cx7g0d5UjDt.jpg",
      release_date: "2023-06-28",
      title: "하나님의 마음",
      video: false,
      vote_average: 7.5,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/g8kCHQzfogy1t1dE9nPBtiFkz64.jpg",
      genre_ids: [53, 878, 18],
      id: 729854,
      original_language: "ko",
      original_title: "콘크리트 유토피아",
      overview:
        "대지진으로 하루아침에 폐허가 된 서울. 모든 것이 무너졌지만 단 한 곳, 황궁 아파트만은 그대로다. 소문을 들은 외부 생존자들이 황궁 아파트로 몰려들자 위협을 느끼기 시작하는 입주민들. 생존을 위해 하나가 된 그들은 새로운 주민 대표 영탁을 중심으로 외부인의 출입을 철저히 막아선 채 아파트 주민만을 위한 새로운 규칙을 만든다. 덕분에 지옥 같은 바깥 세상과 달리 주민들에겐 더 없이 안전하고 평화로운 유토피아 황궁 아파트. 하지만 끝이 없는 생존의 위기 속 그들 사이에서도 예상치 못한 갈등이 시작되는데...",
      popularity: 41.883,
      poster_path: "/7svKr504vaKv93NWaqmqsw9To9C.jpg",
      release_date: "2023-08-09",
      title: "콘크리트 유토피아",
      video: false,
      vote_average: 6,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg",
      genre_ids: [27, 53],
      id: 694,
      original_language: "en",
      original_title: "The Shining",
      overview:
        "소설가인 잭 토랜스는 콜로라도 산맥에 있는 오버룩 호텔의 관리인으로 취직한다. 다음 시즌 준비를 하는 이곳은 겨울 동안 폐쇄되기 때문에 토랜스의 가족들만 호텔에 머물게 된다. 갑자기 몰아친 폭설로 잭과 아내 웬디와 아들과 함께 호텔에 고립되고, 투시와 텔레파시 능력이 있는 잭의 아들 대니는 호텔에 유령이 있으며 유령들이 천천히 아버지를 미치게 하고 있음을 알게 된다. 잭은 과거에 스스로 자신의 아내와 두 딸을 죽인 이곳의 예전 관리인 그레이디의 유령을 만난다. 과거에 있었던 살인사건의 악령에 휘말린 잭은 호텔을 공포의 도가니로 몰아가는데...",
      popularity: 41.818,
      poster_path: "/e3pxD5asVzFMcH3UvmGxolZ7wS.jpg",
      release_date: "2023-06-28",
      title: "샤이닝",
      video: false,
      vote_average: 8.2,
      vote_count: 16033,
    },
    {
      adult: false,
      backdrop_path: "/5iMLD2KE0JQcPchegqSpKstU4CT.jpg",
      genre_ids: [18],
      id: 806368,
      original_language: "en",
      original_title: "The Son",
      overview:
        "성공한 변호사로 뉴욕에서 행복한 새 가정을 이룬 피터는 어느 날, 전처에게 아들 니콜라스가 학교를 나가지 않는다는 소식을 듣는다. 좋은 아버지가 되고 싶었던 피터는 아들을 집으로 데려오지만 애를 쓸수록 두 사람의 사이는 어긋나기만 하는데…",
      popularity: 31.76,
      poster_path: "/yEte5dcKGzcE6N3ZBRlVB8xLtlP.jpg",
      release_date: "2023-07-19",
      title: "더 썬",
      video: false,
      vote_average: 6.6,
      vote_count: 262,
    },
    {
      adult: false,
      backdrop_path: "/7vxuOzbsDgGRKNiB9yzvSHaNlNi.jpg",
      genre_ids: [16, 12, 878],
      id: 1030587,
      original_language: "ja",
      original_title: "映画ドラえもん のび太と空の理想郷",
      overview:
        "어느 날, 하늘 위 떠있는 초승달 모양의 섬을 발견한 진구는 그곳이 자신이 찾고 있던 유토피아가 틀림없다고 생각한다. 그렇게 시공을 초월하는 비행선 ‘타임 제플린’을 타고 섬을 찾아 떠나기로 한 도라에몽과 친구들.여러 시대와 장소를 헤매다 드디어 누구나 완벽해질 수 있는 꿈같은 낙원 ‘파라다피아’에 도착한다. 그곳에서 모든 게 완벽한 퍼펙트 고양이형 로봇 ‘소냐’와 만나 친구가 되지만, 이 낙원에 엄청난 비밀이 숨겨져 있다는 것을 알게 되는데..! 무엇이든 이루어지는 낙원의 섬 ‘파라다피아’의 숨겨진 비밀을 찾기 위한 도라에몽과 친구들의 짜릿한 대모험이 시작된다!",
      popularity: 30.265,
      poster_path: "/pMfGiIseOHHqTXKsL1PanAjFKQv.jpg",
      release_date: "2023-07-08",
      title: "극장판 도라에몽: 진구와 하늘의 유토피아",
      video: false,
      vote_average: 7,
      vote_count: 13,
    },
    {
      adult: false,
      backdrop_path: "/z6GxNP2Z5AyoFfrYKxZWJypfZXJ.jpg",
      genre_ids: [16, 10751],
      id: 823609,
      original_language: "en",
      original_title: "Monster Family 2",
      overview:
        "몬스터에서 인간으로 겨우 돌아온 ‘위시본’ 패밀리!  새 가족이 된 전설 속 몬스터 ‘바바 야가’와 ‘렌필드’의 결혼식 날, 그들은 슈퍼 소녀 ‘밀라’에게 납치당한다. 이들뿐 아니라 드라큘라, 예티, 네시, 그리고 킹 콩가까지!! ‘위시본’ 패밀리는 ‘밀라’에 의해 전 세계 몬스터들이 납치된 것을 알게 되는데…  몬스터들을 구하기 위해 다시 몬스터로 변한 ‘위시본’ 패밀리! 과연 ‘위시본’ 가족은 몬스터들을 구하고 다시 인간으로 돌아갈 수 있을까?",
      popularity: 28.253,
      poster_path: "/9kPiLqqWlwCVL0KGJeM4kcZA9q9.jpg",
      release_date: "2023-08-02",
      title: "몬스터 패밀리 2",
      video: false,
      vote_average: 6.7,
      vote_count: 62,
    },
    {
      adult: false,
      backdrop_path: "/vZaIAIX5XcXLsF4jRSp5x7wsRzn.jpg",
      genre_ids: [80, 28],
      id: 783110,
      original_language: "ko",
      original_title: "밀수",
      overview:
        "1970년대, 바닷가에 인접한 작은 마을 군천엔 절친인 두 해녀 춘자와 진숙, 그리고 진숙의 동생이 살고 있다. 그들은 생계를 위해 항상 물 속에서 해산물들을 채집하는 일을 한다. 하지만 해변 근처에 공장들이 하나 둘 지어지면서, 해녀들의 생계에 곤란이 생기고 선원들은 생계를 위해서 밀수 일에 뛰어들게 된다. 그렇게 시작된 밀수업은 진숙의 가족이 감당하기 벅찰만큼 규모가 커지고 마을의 평화도 점차 깨지기 시작한다.",
      popularity: 21.091,
      poster_path: "/ayLXqPZCu3uaLLhXiqvw5NBb7Lw.jpg",
      release_date: "2023-07-26",
      title: "밀수",
      video: false,
      vote_average: 8,
      vote_count: 2,
    },
  ],
  total_pages: 5,
  total_results: 84,
};
